### ISSUE TITLE
Installing Plugin

### ISSUE THREAD

**Issue by xdsquared** [icecube45/Dash_InfinitiG37#2]
Hey, I have also got dsh and your plugin downloaded, but I don't see how to get dsh to recognize the plugin. I ran the install script again for dash, but I still don't see an option for selecting your plugin. Is there another way to reinstall that I am missing? I also couldn't find where it says to reinstall dsh, I saw other buddies post and gave it a shot. Is there a link for that instruction? The directory I put the plugin in is dash/plugin/vehicle/. Any help would be awesome

**Comment by icecube45** [comment]
That should be the right directory to put the plugin, then recompile afterward. You should be able to select the plugin under the settings menu of the data tab, accessed by clicking on the gear in the top right

**Comment by xdsquared** [comment]
is recompiling the same as just running the install.sh script?

**Comment by icecube45** [comment]
Eh, not the same, but running the install script again will recompile, yes.

**Comment by xdsquared** [comment]
is there an easier way to recompile without having to run the script again?

**Comment by icecube45** [comment]
If you enter the dash build directory and run `make`, it should recompile.

**Comment by xdsquared** [comment]
of course, where the make file is. makes perfect sense, dude tysm. I can see the plug in now. No idea why I couldn't get that working before. I noticed that the name is still climate though. Is there a way to change that?

**Comment by icecube45** [comment]
Are you referring to the tab that gets added to the data page? That's the climate widget (which is blank right now because I'm still reverse engineering some of that stuff), it's necessary though for the climate pop up. I've been working on a plugin refresh though, for a dash update that should be done soonish.

**Comment by xdsquared** [comment]
I happened upon this bit of code in the test.cpp file 
"this->climate = new Climate(*this->arbiter);
 this->climate->setObjectName("**climate**"); "
the word in quotes after setObjectName will change the title of the tab when the plug in is loaded. I am also working on my own plugin and looking at yours has been a great help. Im brand new to c++ so this has become quite the challenge. Thank you again

**Comment by xdsquared** [comment]
when I run your plugin, I can get it to load, but the screen is blank. It shows climate at the top but there's nothing else on the screen. Is that what it is suppose to do?

**Comment by icecube45** [comment]
That's correct - the climate tab is currently blank (as I'm still reverse engineering how to set the climate in the G37), but the blank tab exists so that when you change the climate, you'll get a snackbar popup with the current climate state. The plugin also does things like:
- change to dark theme when the headlights are on
- pause music when the engine turns off

and with a (hopefully soon to be released) update to dash, can display an overall "car status" page.
